name: Update Stats

on:
  schedule:
    # Run at 12am every day
    - cron: '0 0 * * *'
  # Allow running manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Stats Images
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          
      # This step pushes the generated images to your repo
      - name: Commit & Push
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add profile-summary-card-output
          git commit -m "Update stats cards" || exit 0
          git push
